utux:
  motion_converter_node:
    ros__parameters:
      thrusters:
            thruster_0:
              id: 5
              p_motor_offset: [0.5, 0.5, 0.0] #Make sure values are FLOATS or else .as_double_array() will throw an error
              r_motor_dir: [0.0, 0.0, 1.0]    #Make sure values are FLOATS or else .as_double_array() will throw an error
              max_forward_thrust: 100.0
              max_reverse_thrust: -100.0
              # deadband: 0.02
              enabled: true
              inverted: false
            
            thruster_1:
              id: 1
              p_motor_offset: [0.5, -0.5, 0.0] #Make sure values are FLOATS or else .as_double_array() will throw an error
              r_motor_dir: [0.0, 0.0, 1.0]     #Make sure values are FLOATS or else .as_double_array() will throw an error
              max_forward_thrust: 100.0
              max_reverse_thrust: -100.0
              # deadband: 0.02
              enabled: true
              inverted: false
            
            thruster_2:
              id: 2
              p_motor_offset: [-0.5, -0.5, 0.0] #Make sure values are FLOATS or else .as_double_array() will throw an error
              r_motor_dir: [0.0, 0.0, 1.0]     #Make sure values are FLOATS or else .as_double_array() will throw an error
              max_forward_thrust: 100.0
              max_reverse_thrust: -100.0
              # deadband: 0.02
              enabled: true
              inverted: false
            
            thruster_3:
              id: 3
              p_motor_offset: [-0.5, 0.5, 0.0] #Make sure values are FLOATS or else .as_double_array() will throw an error
              r_motor_dir: [0.0, 0.0, 1.0]      #Make sure values are FLOATS or else .as_double_array() will throw an error
              max_forward_thrust: 100.0
              max_reverse_thrust: -100.0
              # deadband: 0.02
              enabled: true
              inverted: false
            
            thruster_4:
              id: 4
              p_motor_offset: [1.0, 1.0, 0.0] #Make sure values are FLOATS or else .as_double_array() will throw an error
              r_motor_dir: [0.707106781186547, -0.707106781186547, 0.0]    #Make sure values are FLOATS or else .as_double_array() will throw an error
              max_forward_thrust: 100.0
              max_reverse_thrust: -100.0
              # deadband: 0.02
              enabled: true
              inverted: false
            
            thruster_5:
              id: 0
              p_motor_offset: [1.0, -1.0, 0.0] #Make sure values are FLOATS or else .as_double_array() will throw an error
              r_motor_dir: [0.707106781186547, 0.707106781186547, 0.0]    #Make sure values are FLOATS or else .as_double_array() will throw an error
              max_forward_thrust: 100.0
              max_reverse_thrust: -100.0
              # deadband: 0.02
              enabled: true
              inverted: false
            
            thruster_6:
              id: 6
              p_motor_offset: [-1.0, -1.0, 0.0] #Make sure values are FLOATS or else .as_double_array() will throw an error
              r_motor_dir: [0.707106781186547, -0.707106781186547, 0.0]    #Make sure values are FLOATS or else .as_double_array() will throw an error
              max_forward_thrust: 100.0
              max_reverse_thrust: -100.0
              # deadband: 0.02
              enabled: true
              inverted: false
            
            thruster_7:
              id: 7
              p_motor_offset: [-1.0, 1.0, 0.0] #Make sure values are FLOATS or else .as_double_array() will throw an error
              r_motor_dir: [0.707106781186547, 0.707106781186547, 0.0]    #Make sure values are FLOATS or else .as_double_array() will throw an error
              max_forward_thrust: 100.0
              max_reverse_thrust: -100.0
              # deadband: 0.02
              enabled: true
              inverted: false