<?xml version="1.0.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>uuv_joystick_hal</name>
  <version>1.0.0</version>
  <description>Joystick hardware abstraction layer for UUV control</description>
  <maintainer email="yxz@todo.todo">yxz</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>uuv_joystick_msgs</depend>
  <exec_depend>joy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>